log:
  level: debug
  format: console
postgres:
  host:     postgres
  port:     5432
  username: initexample
  password: initexample
  database: test
  # sslmode:  string
  preffix:  dev
jwt:
  ttl: 1000m
  crtFile: /app/jwt.crt
  keyFile: /app/jwt.key
  # useMock: mock
rest:
  address: 0.0.0.0:8010
grpc:
  address: 0.0.0.0:8011
