log:
  level: debug
  format: console
jwt:
  crtFile: /app/jwt.crt
  # useMock: mock
rest:
  address: 0.0.0.0:8020
grpc:
  address: 0.0.0.0:8021
prefix: module
mongo:
  debug: shit
  ttl: 10s
  collection: people
  user: admin
  passwd: pass
  database: people
  url: mongodb://mongo:27017/
